CREATE TABLE BOOK (
    UUID CHAR(36) NOT NULL PRIMARY KEY,
    NAME VARCHAR(255),
    AUTHOR VARCHAR(255),
    ISBN VARCHAR(255), 
    CREATED_DATE DATETIME,
    CREATED_BY VARCHAR(255),
    LAST_UPDATED_DATE DATETIME,
    LAST_UPDATED_BY VARCHAR(255)
);

CREATE TABLE BOOK_VERSION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	BOOK_UUID CHAR(36),
	VERSION INT,
	BODY TEXT,
    CONSTRAINT FK_TRAIN_STOP_TRAIN FOREIGN KEY (BOOK_UUID) REFERENCES BOOK(UUID)
);

CREATE TABLE BOOK_COUPON (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    COUPON_NO VARCHAR(255),
    TOKEN VARCHAR(255),
    USED_TO VARCHAR(255), 
    CREATED_DATE DATETIME,
    CREATED_BY VARCHAR(255),
    LAST_UPDATED_DATE DATETIME,
    LAST_UPDATED_BY VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS `EVENT_LOG` (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  UUID CHAR(36) NOT NULL,
  USER_ID VARCHAR(32) NOT NULL,
  EVENT_CLASS_NAME VARCHAR(255) NOT NULL,
  OCCURED_AT DATETIME NOT NULL,
  TARGET_ID CHAR(36),
  BODY LONGTEXT NOT NULL,
  TOPIC VARCHAR(40),
  SEND_QUEUE_STATUS VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `EVENT_IDEMPOTENT_LOG` (
  EVENT_TYPE VARCHAR(190) NOT NULL,
  UNIQUE_KEY VARCHAR(64) NOT NULL,
  TARGET_ID CHAR(36),
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (EVENT_TYPE, UNIQUE_KEY),
  KEY `idx_type_key` (`EVENT_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



